# Generated by Django 6.1.1 on 2026-10-02 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_private', models.BooleanField(default=False)),
                ('invite_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='league',
            name='members',
        ),
        migrations.RemoveField(
            model_name='league',
            name='invite_code',
        ),
        migrations.RemoveField(
            model_name='league',
            name='is_private',
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typer.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='typing_groups', through='typer.GroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LeagueMember',
        ),
    ]
